### ISSUE TITLE
Need Write Access Please

### ISSUE THREAD

**Issue by sfraser** [germantownacademySOS/GASOS#1]
Hi! I have some code ready to push - need write access to this new repo. Thanks!

After that I will hax ur passwords! haha get rekt scrub also I know ur ip sp threr

**Comment by perryprog** [comment]
I gave you permission, but next time please watch your grammar and don't threaten us programmers at the GA Software Creation Facility. As Lead Senior Application Integration Engineer I *do* have permission to block you from accessing our software. 

# **CONSIDER THIS A WARNING**

**Comment by sfraser** [comment]
LOL LOL LOL 😂 😆 🤣

**Comment by perryprog** [comment]
I'm dying

**Comment by sfraser** [comment]
➜  GASOS git:(master) git push
remote: Permission to germantownacademySOS/GASOS.git denied to sfraser.
fatal: unable to access 'https://github.com/germantownacademySOS/GASOS/': The requested URL returned error: 403
➜  GASOS git:(master)

**Comment by sfraser** [comment]
😡

**Comment by perryprog** [comment]
Start a join.me

**Comment by perryprog** [comment]
no wait

**Comment by perryprog** [comment]
[click this](http://join.me/itsrainngtacos)

**Comment by sfraser** [comment]
nice try

**Comment by perryprog** [comment]
What?

**Comment by sfraser** [comment]
was relative URL - went to github

**Comment by perryprog** [comment]
ugh

**Comment by perryprog** [comment]
Click it again

**Comment by sfraser** [comment]
I'll join it I know where you are

**Comment by sfraser** [comment]
Still getting this when I press the "Create a file" button on this repo:

> You’re creating a file in a project you don’t have write access to. Submitting a change will create the file in a new branch in your fork sfraser/GASOS, so you can send a pull request.

**Comment by sfraser** [comment]
Yay you fixed it! I got the invitation and accepted - thanks! 👍🏽😁
